### ISSUE TITLE
Entrega Pedro Igor Oliveira Silva

### ISSUE THREAD

**Issue by pedroeagle** [FGA-GCES/Trabalho-Individual-2020-2#18]
Nome: Pedro Igor Oliveira Silva
Matrícula: 17/0062635
Link: https://github.com/pedroeagle/Trabalho-Individual-2020-2
Site: https://pedroeagle-gces.herokuapp.com

**Comment by renatocoral** [comment]
| Item                                                                                                                                                                                                                                                          | Nota | Observações                                                                                                                                                                    |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1. Containerização                                                                                                                                                                                                                                            |      |                                                                                                                                                                                |
| Container do Back-end                                                                                                                                                                                                                                         | 0,5  | Implementado                                                                                                                                                                   |
| Container do Front-end                                                                                                                                                                                                                                        | 0,5  | Implementado                                                                                                                                                                   |
| Container do Banco de Dados                                                                                                                                                                                                                                   | 0,5  | Implementado                                                                                                                                                                   |
| Automação entre os containers (Docker-compose)                                                                                                                                                                                                                | 1,5  | Implementado                                                                                                                                                                   |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                                                                |
| 2. Integração contínua (Front-end)                                                                                                                                                                                                                            |      |                                                                                                                                                                                |
| Build: Construção completa do ambiente                                                                                                                                                                                                                        | 1,0  | Implementado                                                                                                                                                                   |
| Testes: Os testes automatizados da aplicação devem ser executados                                                                                                                                                                                             | 1,0  | Implementado                                                                                                                                                                   |
| Coleta de métricas: Deverá ser realizada a integração com algum serviço externo de coleta de métricas de qualidade;                                                                                                                                           | 1,0  | Implementado pelo code climate https://codeclimate.com/github/pedroeagle/Trabalho-Individual-2020-2                                                                            |
| Regras de avaliação: O sistema de integração contínua deve exibir as informações de cada pipeline, e impedir que trechos de código que não passem corretamente por todo o processo sejam adicionados à 'branch default' do repositório.                       | 0,4  | O CI foi implementado para rodar nos PRs, mas não há como avaliar se impede o PR de ser aceito, por não haver nenhum PR aberto ou prova de que está funcionando corretamente   |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                                                                |
| 3. Integração contínua (Back-end)                                                                                                                                                                                                                             |      |                                                                                                                                                                                |
| Build: Construção completa do ambiente                                                                                                                                                                                                                        | 1,0  | Implementado                                                                                                                                                                   |
| Testes: Os testes automatizados da aplicação devem ser executados                                                                                                                                                                                             | 1,0  | Implementado                                                                                                                                                                   |
| Coleta de métricas: Deverá ser realizada a integração com algum serviço externo de coleta de métricas de qualidade;                                                                                                                                           | 1,0  | Implementado pelo code climate https://codeclimate.com/github/pedroeagle/Trabalho-Individual-2020-2                                                                            |
| Regras de avaliação: O sistema de integração contínua deve exibir as informações de cada pipeline, e impedir que trechos de código que não passem corretamente por todo o processo sejam adicionados à 'branch default' do repositório.                       | 0,4  | O CI foi implementado para rodar nos PRs, mas não há como avaliar se impede o PR de ser aceito, por não haver nenhum PR aberto ou prova de que está funcionando corretamente   |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                                                                |
| 4. Coverage (Extra)                                                                                                                                                                                                                                           |      |                                                                                                                                                                                |
| Caso cumpra todos os requisitos obrigatórios descritos acima, será atribuída uma pontuação extra para o aluno que configure sua pipeline de modo a coletar a porcentagem de cobertura de testes na aplicação (Back end e Front end).                          | 0,5  | Implementado pelo code cov e code climate https://app.codecov.io/gh/pedroeagle/Trabalho-Individual-2020-2 https://codeclimate.com/github/pedroeagle/Trabalho-Individual-2020-2 |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                                                                |
| 5. Deploy contínuo (Extra)                                                                                                                                                                                                                                    |      |                                                                                                                                                                                |
| Caso cumpra todos os requisitos obrigatórios descritos acima, será atribuída uma pontuação extra para o aluno que configure sua pipeline de modo a publicar a aplicação automaticamente, sempre que um novo trecho de código seja integrado à branch default. | 1,0  | Implementado https://pedroeagle-gces.herokuapp.com/#/                                                                                                                          |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                                                                |
| Total                                                                                                                                                                                                                                                         | 11,3 |                                                                                                                                                                                |
