### ISSUE TITLE
Entrega Caio Oliveira 

### ISSUE THREAD

**Issue by caiooliv** [FGA-GCES/Trabalho-Individual-2020-2#31]
Repositório : [https://github.com/caiooliv/Trabalho-Individual-2020-2](https://github.com/caiooliv/Trabalho-Individual-2020-2)
Nome : Caio Oliveira de Moraes
Matrícula: 15/0120630

**Comment by renatocoral** [comment]
| Item                                                                                                                                                                                                                                                          | Nota | Observações                                                                                                                         |
|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------|-------------------------------------------------------------------------------------------------------------------------------------|
| 1. Containerização                                                                                                                                                                                                                                            |      |                                                                                                                                     |
| Container do Back-end                                                                                                                                                                                                                                         | 0,5  | Implementado.                                                                                                                       |
| Container do Front-end                                                                                                                                                                                                                                        | 0,5  | Implementado.                                                                                                                       |
| Container do Banco de Dados                                                                                                                                                                                                                                   | 0,5  | Implementado.                                                                                                                       |
| Automação entre os containers (Docker-compose)                                                                                                                                                                                                                | 1,5  | Realizado.                                                                                                                          |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                     |
| 2. Integração contínua (Front-end)                                                                                                                                                                                                                            |      |                                                                                                                                     |
| Build: Construção completa do ambiente                                                                                                                                                                                                                        | 0,7  | Não utilizou a construção das versões compiladas dos produtos.                                                                      |
| Testes: Os testes automatizados da aplicação devem ser executados                                                                                                                                                                                             | 1,0  | Os testes são executados no pipeline.                                                                                               |
| Coleta de métricas: Deverá ser realizada a integração com algum serviço externo de coleta de métricas de qualidade;                                                                                                                                           | 0,5  | Aparentemente foi realizada uma integração com codecov mas o aluno não proveu nenhum link de acesso então não é possível confirmar. |
| Regras de avaliação: O sistema de integração contínua deve exibir as informações de cada pipeline, e impedir que trechos de código que não passem corretamente por todo o processo sejam adicionados à 'branch default' do repositório.                       | 0,0  | Não realizado, commits direto na branch principal.                                                                                  |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                     |
| 3. Integração contínua (Back-end)                                                                                                                                                                                                                             |      |                                                                                                                                     |
| Build: Construção completa do ambiente                                                                                                                                                                                                                        | 0,7  | Não utilizou a construção das versões compiladas dos produtos.                                                                      |
| Testes: Os testes automatizados da aplicação devem ser executados                                                                                                                                                                                             | 1,0  | Os testes são executados no pipeline.                                                                                               |
| Coleta de métricas: Deverá ser realizada a integração com algum serviço externo de coleta de métricas de qualidade;                                                                                                                                           | 0,5  | Aparentemente foi realizada uma integração com codecov mas o aluno não proveu nenhum link de acesso então não é possível confirmar. |
| Regras de avaliação: O sistema de integração contínua deve exibir as informações de cada pipeline, e impedir que trechos de código que não passem corretamente por todo o processo sejam adicionados à 'branch default' do repositório.                       | 0,0  | Não realizado, commits direto na branch principal.                                                                                  |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                     |
| 4. Coverage (Extra)                                                                                                                                                                                                                                           |      |                                                                                                                                     |
| Caso cumpra todos os requisitos obrigatórios descritos acima, será atribuída uma pontuação extra para o aluno que configure sua pipeline de modo a coletar a porcentagem de cobertura de testes na aplicação (Back end e Front end).                          | 0,0  | Está como parte dos scripts de automação do github actions entretanto não consegui encontrar o link para acessar em lugar nenhum.   |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                     |
| 5. Deploy contínuo (Extra)                                                                                                                                                                                                                                    |      |                                                                                                                                     |
| Caso cumpra todos os requisitos obrigatórios descritos acima, será atribuída uma pontuação extra para o aluno que configure sua pipeline de modo a publicar a aplicação automaticamente, sempre que um novo trecho de código seja integrado à branch default. | 0,0  | Não realizado.                                                                                                                      |
|                                                                                                                                                                                                                                                               |      |                                                                                                                                     |
| Total                                                                                                                                                                                                                                                         | 7,4  |                                                                                                                                     |
